/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordguessinggame;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        WordChoser chooser = new WordChoser();
        Game game = new Game(chooser);
        Masker masker = new Masker(game);
        System.out.println("Welcome! Today the word to guess is: ");

        do{
            System.out.println(masker.getMaskedWord(game));

            System.out.println("Enter one letter to guess: ");
            Scanner scanner = new Scanner(System.in);
            
            Character guess = scanner.nextLine().charAt(0);
            guess = Character.toUpperCase(guess);
            Boolean result = game.guessLetter(guess);
            if(result){
                System.out.print("Correct!");
                
            }else{
                System.out.println("Incorrect...");
            }

            if(game.isGameWon()){
                System.out.println("You Won!!");

                return;
            }else if(game.isGameLost()){
                System.out.println("You Lost Unfortunately");
                return;

            }

        }while(game.remaining_attempts >= 1);

    }
}
